### ISSUE TITLE
張數無法設定

### ISSUE THREAD

**Issue by bluefatcat1993** [youshenlin/ticket_kktix#1]
`張數無論設定幾張，都會自動選最大張數非指定張數`

然後，找了好久，終於有 kktix 的 chrome 瀏覽器的搶票插件了 !!
讚讚！請務必繼續保持更新及優化 💯

還有，使用這個購票工具插件
不會被 kktix 的驗證碼 Google reCAPTCHA 偵測為機器人而啟動驗證碼
可直接完成購買流程，真是太棒了！

**Comment by bear3z** [comment]
張數設定並沒有故障喔～若你選完張數沒有進到下一個頁面他就會重複執行前面的動作

**Comment by coolbar1993** [comment]
所以這部分，可能要修正一下...
